//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFKNGK1.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Виды_расходов
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Виды_расходов()
        {
            this.Покупки = new HashSet<Покупки>();
        }
    
        public int ID_категории { get; set; }
        public string Название_категории { get; set; }
        public string Описание { get; set; }
        public Nullable<decimal> Предельная_сумма { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Покупки> Покупки { get; set; }
    }
}
