//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFKNGK1.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Покупки
    {
        public int ID_покупки { get; set; }
        public Nullable<int> ID_сотрудника { get; set; }
        public Nullable<int> ID_категории_расходов { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<decimal> Сумма { get; set; }
    
        public virtual Виды_расходов Виды_расходов { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
